version: '2'

networks:
  lan_network:
    driver: bridge

services:
 digitaltoys:
  hostname: digit
  build: ./DigitalToys 
  ports:
    - 8787:8080
  networks:
    - lan_network
 flask_login:
  hostname: flask
  build: ./flask_log_in
  links: 
    - db:mysql
  depends_on:
    - db
  ports:
    - 5000:5000
  environment: 
    DB_USER_USERNAME: hme
    DB_USER_PASSWORD: password
  networks:
    - lan_network

 web_application:
  hostname: web
  image: centos/httpd 
  links: 
    - db:mysql
  depends_on:
    - db
  ports:
    - 8080:80
  volumes:
    - /var/log/centos-web:/var/log/httpd
  networks:
    - lan_network
 db:
  hostname: mysql
  image: astondevops/docker-mysql-5.6 
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes: 
    - /var/log/mysql-db:/var/log/mysql
  networks:
    - lan_network

 phpmyadmin:
  hostname: phpmyadmin
  image: nazarpc/phpmyadmin
  links: 
    - db:mysql
  depends_on:
    - db
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: password 
  networks:
    - lan_network
